#!/usr/bin/env bash
set -euo pipefail

# Week4：异步任务 worker。必须与 Gateway 使用完全相同的 upstream 与 Redis 配置。

export INFERENCE_BACKEND="${INFERENCE_BACKEND:-vllm}"

export VLLM_BASE_URL="${VLLM_BASE_URL:-http://127.0.0.1:8002/v1}"
export VLLM_MODEL_NAME="${VLLM_MODEL_NAME:-Seed-OSS-36B-Instruct-W8A8-Primary}"
export VLLM_TIMEOUT_SECONDS="${VLLM_TIMEOUT_SECONDS:-300}"
export VLLM_ENABLE_SEED_THINKING_BUDGET="${VLLM_ENABLE_SEED_THINKING_BUDGET:-true}"

export VLLM_FALLBACK_BASE_URL="${VLLM_FALLBACK_BASE_URL:-http://127.0.0.1:8010/v1}"
export VLLM_FALLBACK_MODEL_NAME="${VLLM_FALLBACK_MODEL_NAME:-Seed-OSS-36B-Instruct-W8A8-Fallback}"
export VLLM_FALLBACK_TIMEOUT_SECONDS="${VLLM_FALLBACK_TIMEOUT_SECONDS:-300}"

export RESILIENCE_STATE_STORE="${RESILIENCE_STATE_STORE:-redis}"
export RESILIENCE_REDIS_URL="${RESILIENCE_REDIS_URL:-redis://127.0.0.1:6379/0}"
export RESILIENCE_REDIS_KEY_PREFIX="${RESILIENCE_REDIS_KEY_PREFIX:-ai-inference:week4:resilience}"

export JOB_QUEUE_REDIS_URL="${JOB_QUEUE_REDIS_URL:-$RESILIENCE_REDIS_URL}"
export JOB_QUEUE_KEY_PREFIX="${JOB_QUEUE_KEY_PREFIX:-ai-inference:week4:jobs}"
export JOB_QUEUE_CONSUMER_GROUP="${JOB_QUEUE_CONSUMER_GROUP:-week4-workers}"

export JOB_WORKER_NAME="${JOB_WORKER_NAME:-week4-worker-$(hostname)}"
export JOB_WORKER_BATCH_SIZE="${JOB_WORKER_BATCH_SIZE:-10}"
export JOB_WORKER_METRICS_HOST="${JOB_WORKER_METRICS_HOST:-0.0.0.0}"
export JOB_WORKER_METRICS_PORT="${JOB_WORKER_METRICS_PORT:-9101}"

exec python -m app.job_worker
