apiVersion: v1
kind: Service
metadata:
  name: inference-nginx
  namespace: ai-inference
spec:
  selector:
    app: inference-nginx
  ports:
    - name: http
      port: 8080
      targetPort: http
  type: ClusterIP
