apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasource
  namespace: ai-inference
data:
  prometheus.yaml: |
    apiVersion: 1
    datasources:
      - name: Prometheus
        uid: prometheus
        type: prometheus
        access: proxy
        url: http://prometheus:9090
        isDefault: true
        editable: false
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-dashboard-provider
  namespace: ai-inference
data:
  dashboards.yaml: |
    apiVersion: 1
    providers:
      - name: week3
        orgId: 1
        folder: Week3
        type: file
        disableDeletion: true
        editable: false
        options:
          path: /var/lib/grafana/dashboards
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  namespace: ai-inference
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
        - name: grafana
          image: grafana/grafana:12.4.4
          imagePullPolicy: Never
          env:
            - name: GF_SECURITY_ADMIN_USER
              value: admin
            - name: GF_SECURITY_ADMIN_PASSWORD
              value: admin
            - name: GF_USERS_ALLOW_SIGN_UP
              value: "false"
          ports:
            - name: http
              containerPort: 3000
          volumeMounts:
            - name: datasource
              mountPath: /etc/grafana/provisioning/datasources
              readOnly: true
            - name: provider
              mountPath: /etc/grafana/provisioning/dashboards
              readOnly: true
            - name: dashboard
              mountPath: /var/lib/grafana/dashboards
              readOnly: true
      volumes:
        - name: datasource
          configMap:
            name: grafana-datasource
        - name: provider
          configMap:
            name: grafana-dashboard-provider
        - name: dashboard
          configMap:
            name: grafana-dashboard-week3
---
apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: ai-inference
spec:
  selector:
    app: grafana
  ports:
    - name: http
      port: 3000
      targetPort: http
