apiVersion: v1
kind: Service
metadata:
  name: inference-gateway
  namespace: ai-inference
spec:
  selector:
    app: inference-gateway
  ports:
    - name: http
      port: 8000
      targetPort: http
  type: ClusterIP
