import os


INFERENCE_BACKEND = os.getenv("INFERENCE_BACKEND", "mock")

MODEL_NAME = os.getenv(
    "MODEL_NAME",
    "Qwen/Qwen2.5-0.5B-Instruct",
)

VLLM_BASE_URL = os.getenv(
    "VLLM_BASE_URL",
    "http://127.0.0.1:8001/v1",
)

VLLM_MODEL_NAME = os.getenv(
    "VLLM_MODEL_NAME",
    MODEL_NAME,
)

VLLM_TIMEOUT_SECONDS = float(
    os.getenv("VLLM_TIMEOUT_SECONDS", "300")
)

VLLM_ENABLE_SEED_THINKING_BUDGET = (
    os.getenv("VLLM_ENABLE_SEED_THINKING_BUDGET", "false").lower() == "true"
)

MOCK_CPU_BURN_MS = int(
    os.getenv("MOCK_CPU_BURN_MS", "0")
)


TRANSFORMERS_LOAD_IN_8BIT = (
    os.getenv("TRANSFORMERS_LOAD_IN_8BIT", "false").lower() == "true"
)

TRANSFORMERS_DEVICE_MAP = os.getenv(
    "TRANSFORMERS_DEVICE_MAP",
    "auto",
)

TRANSFORMERS_DEFAULT_THINKING_BUDGET = int(
    os.getenv("TRANSFORMERS_DEFAULT_THINKING_BUDGET", "0")
)

RESILIENCE_RETRY_ATTEMPTS = int(
    os.getenv("RESILIENCE_RETRY_ATTEMPTS", "1")
)

RESILIENCE_RETRY_BACKOFF_SECONDS = float(
    os.getenv("RESILIENCE_RETRY_BACKOFF_SECONDS", "0.2")
)

RESILIENCE_FAILURE_THRESHOLD = int(
    os.getenv("RESILIENCE_FAILURE_THRESHOLD", "3")
)

RESILIENCE_RECOVERY_TIMEOUT_SECONDS = float(
    os.getenv("RESILIENCE_RECOVERY_TIMEOUT_SECONDS", "20")
)

VLLM_FALLBACK_BASE_URL = os.getenv(
    "VLLM_FALLBACK_BASE_URL",
    "",
).rstrip("/")

VLLM_FALLBACK_MODEL_NAME = os.getenv(
    "VLLM_FALLBACK_MODEL_NAME",
    VLLM_MODEL_NAME,
)

RESILIENCE_FALLBACK_THINKING_BUDGET = int(
    os.getenv("RESILIENCE_FALLBACK_THINKING_BUDGET", "512")
)
